name: Windows Nightly

on:
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC    
  workflow_dispatch:

jobs:
  check_date:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check_recent_commits.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for recent commits
        id: check_recent_commits
        run: |
          # Get the timestamp of the last commit
          last_commit_timestamp=$(git log -1 --format=%at)
          # Get the current timestamp
          current_timestamp=$(date +%s)
          # Calculate the difference in seconds
          difference=$((current_timestamp - last_commit_timestamp))

          # Check if the last commit was within the last 24 hours (86400 seconds)
          if [ "$difference" -lt 86400 ]; then
            echo "::set-output name=should_run::true"
          else
            echo "::set-output name=should_run::false"
          fi
  nightly_build:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run == 'true' }}
    runs-on: windows-2022

    steps:
    - name: Checkout xLights
      run: git clone https://github.com/xLightsSequencer/xLights.git C:/xLights/ --depth 1  --depth=1 --shallow-submodules --recurse-submodules

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: install ISPC
      uses: ispc/install-ispc-action@main
      with:
        version: 1.27.0
            
#    - name: install Inno
#      run: choco install innosetup   
      
    - name: install python dependency
      run: pip install in_place  
      
    - name: generate nightly version number
      working-directory: C:/xLights/build_scripts/msw
      run: python WriteNightlyVersionFiles.py  
     
    - name: Download wxWidgets
      run: 
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b master https://github.com/xLightsSequencer/wxWidgets C:/wxWidgets/

    - name: Build wxWidgets
      working-directory: C:/wxWidgets/
      run: msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"
      
    - name: Build All
      shell: cmd
      working-directory: C:/xLights/build_scripts/msw
      run: call build_VS_x64_skip_libltc.cmd
      
    - name: Build Installer
      working-directory: C:/xLights/build_scripts/msw
      run: ISCC.exe xLights_4_64bit_VS.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: xLights_x64_Installer
        path: 'C:\xLights\build_scripts\msw\output\**'
        
    - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "nightly"
        title: "${{ steps.version.outputs.version }}"
        files: |        
          C:/xLights/build_scripts/msw/output/*.exe

